import { useRouter } from "next/router";
import Head from "next/head";
import React from "react";

function Blog(props) {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Blog - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Blog HomePage
      <p>
        <code>Go to </code>
        <button onClick={() => router.push("/")}>Home</button>
        <button onClick={() => router.back()}>Back Home</button>
      </p>
    </div>
  );
}

export default Blog;
